version: '3'
services:
  es01:
    image: elasticsearch:7.17.9
    container_name: es-01
    environment:
      - cluster.name=es-cluster
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
volumes:
  es:
    driver: local
networks:
  elasticsearch:
    driver: bridge
