version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: es-01
    environment:
      - cluster.name=es-cluster
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
volumes:
  es:
    driver: local
networks:
  elasticsearch:
    driver: bridge
